/* eslint-plugin-disable notice */

module.exports = [
  ['Abril Fatface'],
  ['Alfa Slab One'],
  ['Baloo'],
  ['Berkshire Swash'],
  ['Black Ops One'],
  ['Bungee'],
  ['Chicle'],
  ['Coiny'],
  ['Creepster'],
  ['Fascinate Inline'],
  ['Faster One'],
  ['Fontdiner Swanky'],
  ['Freckle Face'],
  ['Fredoka One'],
  ['Frijole'],
  ['Gravitas One'],
  ['Lilita One'],
  ['Limelight'],
  ['Luckiest Guy'],
  ['Mogra'],
  ['Nosifer'],
  ['Pacifico'],
  ['Poller One'],
  ['Press Start 2P'],
  ['Racing Sans One'],
  ['Rakkas'],
  ['Rammetto One'],
  ['Ranchers'],
  ['Righteous'],
  ['Ruslan Display'],
  ['Sarina'],
  ['Shojumaru'],
  ['Shrikhand'],
  ['Sigmar One'],
  ['Skranji'],
  ['Spicy Rice'],
  ['Squada One'],
  ['Titan One'],
  ['Vampiro One'],
  ['Vast Shadow'],
  ['ZCOOL KuaiLe'],
];
